name: Calculator Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Verify Python version
      run: python --version

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pytest

    - name: Run tests
      run: pytest 
